const monsters = {
    Adventurer: {
        position: {x:260, y:280}, 
        image: {src: "./img/playerBattle.png"}, 
        frames: {max:4, hold:20}, 
        animate: true, 
        name:"Adventurer",
        health: 100,
        attacks: [attacks.Brawl, attacks.Lucky]
    },
    Momo: {
        position: {x:800, y:100}, 
        image: {src: "./img/enemyMushroom.png"}, 
        frames: {max:4, hold:20}, 
        animate: true, 
        health: 100,
        damage: 10,
        armour: 0,
        isEnemy: true, 
        name:"Momo",
        attacks: [attacks.Tackle],
        xp: 15,
        drops: ["mixed seeds"],
        rareDrops: ["bow"],
        gold: 10,
    },
    Draggle: {
        position: {x:800, y:100}, 
        image: {src: "./img/draggleSprite.png"}, 
        frames: {max:4, hold:20}, 
        animate: true, 
        health: 100,
        damage: 10,
        armour: 0,
        isEnemy: true, 
        name:"Draggle",
        attacks: [attacks.Tackle, attacks.Dive],
        xp: 20,
        drops: [ "leather" ],
        rareDrops: ["wand"],
        gold: 15,
    },
    Emby: {
        position: {x:800, y:100}, 
        image: {src: "./img/embySprite.png"}, 
        frames: {max:4, hold:20}, 
        animate: true, 
        health: 120,
        damage: 12,
        armour: 0,
        isEnemy: true, 
        name:"Emby",
        attacks: [attacks.Tackle, attacks.Fireball],
        xp: 25,
        drops: ["coal"],
        rareDrops: ["sword"],
        gold: 20,
    },
    Woodle: {
        position: {x:785, y:65}, 
        image: {src: "./img/enemyWoodle.png"}, 
        frames: {max:4, hold:20}, 
        animate: true, 
        health: 150,
        damage: 15,
        armour: 1,
        isEnemy: true, 
        name:"Woodle",
        attacks: [attacks.Tackle, attacks.Fireball],
        xp: 30,
        drops: ["wood"],
        rareDrops: ["sandals"],
        gold: 25,
    },
    Rocky: {
        position: {x:740, y:60}, 
        image: {src: "./img/enemyRocky.png"}, 
        frames: {max:6, hold:20}, 
        animate: true, 
        health: 180,
        damage: 18,
        armour: 2,
        isEnemy: true, 
        name:"Rocky",
        attacks: [attacks.Tackle, attacks.Fireball],
        xp: 40,
        drops: ["granite ore"],
        rareDrops: ["cap"],
        gold: 35,
    },
    Beradin: {
        position: {x:780, y:55}, 
        image: {src: "./img/enemyBeradin.png"}, 
        frames: {max:4, hold:20}, 
        animate: true, 
        health: 200,
        damage: 20,
        armour: 3,
        isEnemy: true, 
        name:"Beradin",
        attacks: [attacks.Tackle, attacks.Fireball],
        xp: 50,
        drops: ["coal"],
        rareDrops: ["robe"],
        gold: 45,
    },
}